---
title: "Assignment 2"
author: "Isabel Hojman"
date: "14/10/2017"
output: html_document
---

## EXERCISE 1

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("functions.R")
```

```{r}
print(sum_column(iris, "Sepal.Length"))
print(sum_column(iris, "Species"))
print(sum_column(warpbreaks, "breaks"))
```

```{r}
print(my_sum(iris$Sepal.Length))
print(my_sum(iris$Species))
print(my_sum(warpbreaks$breaks))
```

```{r}
print(sum_divided_by(iris$Sepal.Length, 12))
print(sum_divided_by(iris$Species, 22))
print(sum_divided_by(iris$Sepal.Length, "Not numeric"))
print(sum_divided_by(warpbreaks$breaks, -12))
```

```{r}
print(my_mean(iris$Sepal.Length))
print(my_mean(iris$Species))
print(my_mean(warpbreaks$breaks))
```

## EXERCISE 2

```{r}
print(grouped_violin_plot(iris, "Sepal.Length", "Species"))
```

```{r}
p <- grouped_violin_plot(iris, "Sepal.Length", "Species")
# YOUR CODE HERE: Change the colour scheme for the interior of the three violin plots
#                 to anything else at all.
p <- p + ggplot2::scale_fill_brewer(palette="PRGn")
# YOUR CODE HERE: Add a main title that says "Iris data".
p <- p + ggplot2::ggtitle("New Iris Data")
print(p)
```

## EXERCISE 3

```{r}
difference_in_medians(iris, "Sepal.Width", "Species", "versicolor", "virginica")
difference_in_medians(iris, "Sepal.Width", "Species", "virginica", "virginica")
```

```{r}
iris$Sepal.Width[1:10]
if(!exists(".Random.seed")) set.seed(NULL)
previous_seed <- .Random.seed
set.seed(1)
randomize(iris, "Sepal.Width")$Sepal.Width[1:10]
randomize(iris, "Species")$Species[1:10]
randomize(iris, "Species")$Sepal.Width[1:10]
set.seed(previous_seed)
```


